#!/bin/sh

if [ -z "$GAP" ] 
then
        GAP=gap
fi


CPU_INFO=$(cat /proc/cpuinfo|grep 'model name'|head -n 1|cut -d: -f 2)
OS_INFO="Linux ($(uname -vr))"
GAP_INFO=$($GAP -h 2>&1 |grep Version|sed -e 's/.*Version //')

cat <<-EOF 
	<#GAPDoc Label="timing">
		Timing results are obtained on an $CPU_INFO processor running
		$OS_INFO 
		and using GAP $GAP_INFO.
	<#/GAPDoc>
EOF
