#!/bin/sh
######################### BEGIN COPYRIGHT MESSAGE #########################
# GBNP - computing Gröbner bases of noncommutative polynomials
# Copyright 2001-2010 by Arjeh M. Cohen, Dié A.H. Gijsbers, Jan Willem
# Knopper, Chris Krook. Address: Discrete Algebra and Geometry (DAM) group
# at the Department of Mathematics and Computer Science of Eindhoven
# University of Technology.
# 
# For acknowledgements see the manual. The manual can be found in several
# formats in the doc subdirectory of the GBNP distribution. The
# acknowledgements formatted as text can be found in the file chap0.txt.
# 
# GBNP is free software; you can redistribute it and/or modify it under
# the terms of the Lesser GNU General Public License as published by the
# Free Software Foundation (FSF); either version 2.1 of the License, or
# (at your option) any later version. For details, see the file 'LGPL' in
# the doc subdirectory of the GBNP distribution or see the FSF's own site:
# http://www.gnu.org/licenses/lgpl.html
########################## END COPYRIGHT MESSAGE ##########################
# force UTF-8 output
LANG=en_UK.UTF-8
export LANG

#checks for $GAP
if [ -z "$GAP" ] 
then
	GAP=gap
fi

mkdir -p build/pkg/gbnp
for i in * 
do 
  if [ "${i}" != "build" ] 
  then
    ln -sf $(/bin/pwd)/"${i}" build/pkg/gbnp/"${i}";
  fi
done
{ echo 'SaveWorkspace("build/gbnp.wks");'; } | eval ${GAP} -l \\\;$(/bin/pwd)/build 
gzip -9f build/gbnp.wks

echo "It is now possible to set \$GAP with the command"
echo
echo "export GAP=\"${GAP} -L $(/bin/pwd)/build/gbnp.wks -l \\;$(/bin/pwd)/build\""
