#!/bin/sh

while [ -n "$1" ] ; do
        cat <<-EOF
	LoadPackage("gbnp");
	GBNP.ConfigPrint();
	
	# reset Info levels
	SetInfoLevel(InfoGBNP,0);
	SetInfoLevel(InfoGBNPTime,0);

	# reset options
	GBNP.ClearOptions();
EOF
        echo "#START_TEST(\"GBNP $1\");" 

	cat $1

	echo "#STOP_TEST(\"$1.g\",10000);"

	shift
done
