#!/bin/sh
######################### BEGIN COPYRIGHT MESSAGE #########################
# GBNP - computing Gröbner bases of noncommutative polynomials
# Copyright 2001-2010 by Arjeh M. Cohen, Dié A.H. Gijsbers, Jan Willem
# Knopper, Chris Krook. Address: Discrete Algebra and Geometry (DAM) group
# at the Department of Mathematics and Computer Science of Eindhoven
# University of Technology.
# 
# For acknowledgements see the manual. The manual can be found in several
# formats in the doc subdirectory of the GBNP distribution. The
# acknowledgements formatted as text can be found in the file chap0.txt.
# 
# GBNP is free software; you can redistribute it and/or modify it under
# the terms of the Lesser GNU General Public License as published by the
# Free Software Foundation (FSF); either version 2.1 of the License, or
# (at your option) any later version. For details, see the file 'LGPL' in
# the doc subdirectory of the GBNP distribution or see the FSF's own site:
# http://www.gnu.org/licenses/lgpl.html
########################## END COPYRIGHT MESSAGE ##########################

if [ -z "$1" ] || ! [ -f "$1.txt" ] 
then
	echo "Usage $0 <file>"
	echo "Where file does not contain the extension (.g or .gi[id])" 
	exit 1;
fi

echo "gap> START_TEST(\"GBNP $1\");" >"$1".test
cat "$1".txt >>"$1".test
echo >>"$1".test
echo "gap> STOP_TEST(\"$1.g\",10000);" >>"$1".test
